name: longmethyl
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7.12
  - pip
  - scipy
  - numpy>=1.19.2
  - minimap2>=2.23
  - parallel=20170422
  - samtools>=1.12
  - statsmodels>=0.12.2
  - h5py=2.8
  - ont-tombo=1.5.1
  - pandas
  - scikit-learn
  - tensorflow=1.13.1
  - pip:
    - deepsignal==0.2.0
    - protobuf<=3.20.1
